add favicon
ewasm/etherchain-light pull request #61
Opened 2018-11-14 16:40 UTC by Alicia-isa

2018-11-14 16:56 UTC, axic commented on views/layout.pug
> +    link(rel='shortcut icon' href='/explorer/images/favicon.ico')
Thanks! I think lately favicon's don't need to be this horrible tiny ICO format, but can be larger PNGs.

2018-11-14 16:57 UTC, axic requested changes
Please use a larger PNG icon.

2019-01-31 11:59 UTC, axic commented
@hugo-dc could you address this?

2019-01-31 18:47 UTC, hugo-dc commented
sure

2019-02-01 00:11 UTC, axic approved these changes

2019-02-01 00:11 UTC, merged